### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'success')

### ISSUE THREAD

**Issue by xiazeyu** [Difegue/Tsukihi#12]
![Snipaste_2022-04-16_17-09-39](https://user-images.githubusercontent.com/10560038/163669269-9b281dd8-08d0-481b-bf4d-7d30e6a6399a.png)
Is it caused by some API changes of LANraragi?

**Comment by xiazeyu** [comment]
Its download function still works pretty well, but the pop-up window itself is quite annoying.

**Comment by Difegue** [comment]
I've noticed this on Firefox as well lately, not sure where it's coming from.

**Comment by xiazeyu** [comment]
Found the source of this bug:
In https://github.com/Difegue/LANraragi/commit/d0c2b5fa29f90906f5bd11ecd3312ac991c51034, `/api/minion/:jobid/detail` is introduced to replace `/api/minion/:jobid`. 
Current `/api/minion/:jobid` returns:
```json
{
    "error": null,
    "state": "finished",
    "task": "download_url"
}
```

But what Tsukihi requires is:
```json
{
    "args": [
        "https://domain.com",
        null
    ],
    "attempts": "5",
    "children": [],
    "created": "42",
    "delayed": "42",
    "finished": "42",
    "id": "1",
    "notes": {},
    "parents": [],
    "priority": "1",
    "queue": "default",
    "result": {
        "id": "dummy",
        "message": "URL already downloaded!",
        "success": 0,
        "url": "domain.com"
    },
    "retried": null,
    "retries": "0",
    "started": "42",
    "state": "finished",
    "task": "download_url",
    "worker": "5"
}
```

**Comment by Difegue** [comment]
Yup, good analysis: I forgot to fix tsukihi after introducing this endpoint and nerfing the original one.
Thanks! I'll release an updated version of the plugin after making the matching LRR release.
