### ISSUE TITLE
Support Manifest V3

### ISSUE THREAD

**Issue by xiazeyu** [Difegue/Tsukihi#14]
Unrecognized manifest key 'browser_specific_settings'.

![CleanShot 2023-11-13 at 00 44 29@2x](https://github.com/Difegue/Tsukihi/assets/10560038/3ac5a8f2-a3c7-4f6d-95d9-0e976e748e3d)

Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

![CleanShot 2023-11-13 at 00 44 48@2x](https://github.com/Difegue/Tsukihi/assets/10560038/ac3935f0-3dae-4cf9-b2d6-9ec6669f8033)

**Comment by Difegue** [comment]
That first one is firefox-specific code, no big deal.  

Number two is fine until 2024 as per google's resumed deprecation timeline for manifest v2 (sigh): https://developer.chrome.com/blog/resuming-the-transition-to-mv3/ 

I'll get to pushing a new update with the manifest bumped when firefox supports it.
