### ISSUE TITLE
Double URLs for source when using "Download This Tab"

### ISSUE THREAD

**Issue by KamillaPup** [Difegue/Tsukihi#16]
I'm using version 1.2 and when I click on Download This Tab, it tags the same URL but one with https:// and one without. as you can see below.
![image](https://github.com/Difegue/Tsukihi/assets/26353056/b972fa75-aaa8-42aa-9160-b484036872c2)
one as `source:https://exhentai.org/g/111111` and `source:exhentai.org/g/111111`
This doesn't happen when using the Download URL within Lanraragi.

**Comment by Difegue** [comment]
This was a server bug, I believe it's fixed now: https://github.com/Difegue/LANraragi/pull/921
