### ISSUE TITLE
Unable to download from EH

### ISSUE THREAD

**Issue by bossanovaorca** [Difegue/Tsukihi#20]
when attempting to download from EH or ExH the extension immediately returns `(Error: Couldn't retrieve archiver key for gID <gID> gToken <gToken>)`

likely related to https://github.com/Difegue/LANraragi/issues/1101

**Comment by Difegue** [comment]
Not an issue with the extension.

**Comment by glop102** [comment]
Context for others stumbling in here: the root problem is E-H changing how things work on their site. The plugin that does downloading is in lanraragi. The issue is theoretically fixed in https://github.com/Difegue/LANraragi/issues/1101
