### ISSUE TITLE
Only run on whitelisted domains

### ISSUE THREAD

**Issue by nonamethanks** [Difegue/Tsukihi#3]
I've noticed looking at the server logs that whenever I open a new tab on my browser, the extension calls the server, and logs:
`[Plugin System] [info] No login plugin specified, returning empty UserAgent.`

The user should be able to specify a whitelist outside of which the extension should not run, or the extension should just be able to get the supported domains from the server itself and not bother in other sites.

**Comment by Difegue** [comment]
As said in #2, the download system doesn't really have a concept of "supported domains", so it'll try to download any url thrown at it.  

Now in practice, downloads will realistically only work with direct file URLs or URLs that have a matching downloader plugin, so it'd be possible to check `api/plugins/download` on the extension side to get a list of URL regexes to map against:  

![image](https://user-images.githubusercontent.com/8237712/115610146-c10e8a00-a2e8-11eb-88fe-5caa09243797.png)

**Comment by Difegue** [comment]
The automatic check when opening a new tab now only occur if the URL has a matching regex in the server's downloader list.  
It's always possible to bypass this and perform a check manually by clicking "Recheck" in the popup. 👏
