### ISSUE TITLE
Normalize e-h and ex links

### ISSUE THREAD

**Issue by koma-cute** [Difegue/Tsukihi#5]
Visiting the same gallery on e-h or ex results in tsukihi thinking the gallery has not been downloaded before.

**Comment by Difegue** [comment]
Fixing this on the extension side would basically be an ugly hack, but the alternative would be to add two `source:` tags on the server side for each domain when it does a download, which is even worse...  

I'm pretty sure only ex/e-h has that scenario, so fixing it in this repo as a special exception would probably be fine.

**Comment by Difegue** [comment]
Fixed server-side in https://github.com/Difegue/LANraragi/commit/927f0699d27c98790cf0bcce48f2d437bbbdeced .
