### ISSUE TITLE
Limit tab operation to supported sites

### ISSUE THREAD

**Issue by koma-cute** [Difegue/Tsukihi#8]
Currently, Tsuhiki runs on every page, and sends the URL to be searched. From both a privacy and efficiency point of view, this should be limited to only run on pages the plugins support. This could either be baked directly into the manifest, or as an optional list of sites in the settings. Given 99% of users aren't going to be running custom downloader scripts, I think the former is a better option, as they can build their own extension or mainline their plugin while security is better controlled at the browser level.

**Comment by Difegue** [comment]
Clone of #3, see my comment there 👍
